# Generated by Django 4.0.4 on 2024-06-16 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_turno'),
        ('asesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('documentos', 'Documentos'), ('caja', 'Caja'), ('asesorias', 'Asesorías'), ('servicios', 'Servicios')], max_length=20)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('documentos', 'Documentos'), ('caja', 'Caja'), ('asesorias', 'Asesorías'), ('servicios', 'Servicios')], max_length=20)),
                ('estado', models.CharField(default='atendido', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('documentos', 'Documentos'), ('caja', 'Caja'), ('asesorias', 'Asesorías'), ('servicios', 'Servicios')], max_length=20)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
