# Generated by Django 4.0.4 on 2024-06-16 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0002_turnopendiente_turnoatendido_asesorarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnopendiente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='turnopendiente',
            name='apellido_cliente',
            field=models.CharField(default=1, max_length=100, verbose_name='Apellido del Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnopendiente',
            name='cliente_cedula',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Cédula del Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnopendiente',
            name='nombre_cliente',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre del Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnopendiente',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
