# Generated by Django 4.0.4 on 2024-06-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0003_remove_turnopendiente_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnoatendido',
            name='numero_turno',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turnopendiente',
            name='numero_turno',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
