# Generated by Django 4.0.4 on 2024-06-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesores', '0004_turnoatendido_numero_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnoatendido',
            name='numero_turno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='turnopendiente',
            name='numero_turno',
            field=models.CharField(max_length=10),
        ),
    ]
