# Generated by Django 4.0.4 on 2024-06-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0003_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesor',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
